/// <reference types="Cypress" />

const uuidv4 = require('uuid-v4');

describe("ลงทะเบียน", () => {
    it("ลงทะเบียนผู้ใช้ใหม่", ()=> {
        cy.visit('/pages/register')
        cy.get(':nth-child(1) > .row > :nth-child(1) > .form-control')
        .type('Narongsak')
        cy.get(':nth-child(2) > .form-control')
        .type('Mala')
        cy.get(':nth-child(2) > .row > .col-md-12 > .form-control')
        .type(`narongsak.mala.${uuidv4().substr(0,5)}@dga.or.th`)
        cy.get('#passwordptooltip')
        .type('Password1234')
        cy.get(':nth-child(4) > .row > .col-md-12 > .form-control')
        .type('0817264466',{force: true})
        cy.get('#min_id')
        .select('สำนักนายกรัฐมนตรี', {force: true})
        .should('have.value', '01')
        cy.get('#dep_id')
        .select('สำนักงานพัฒนารัฐบาลดิจิทัล (องค์การมหาชน)')
        cy.get(':nth-child(7) > .row > .col-md-12 > .form-control')
        .select('สำนักงานพัฒนารัฐบาลดิจิทัล (องค์การมหาชน) สพร.')
        .should('have.value', '0111013900000')
        cy.get('.custom-control > a.white')
        .click()
        cy.get('.modal-footer > .btn')
        .click()
        cy.get('#acception')
        .click({force: true})
        cy.get('.btn-pink')
        .click({force: true})

        cy.get(':nth-child(1) > .row > :nth-child(1) > .form-control')
        .should('have.value', '')
        cy.get(':nth-child(2) > .form-control')
        .should('have.value', '')
        cy.get(':nth-child(2) > .row > .col-md-12 > .form-control')
        .should('have.value', '')
        cy.get('#passwordptooltip')
        .should('have.value', '')
        cy.get(':nth-child(4) > .row > .col-md-12 > .form-control')
        .should('have.value', '')
        cy.get('#min_id')
        .should('have.value', '--เลือกกระทรวง--')
        cy.get('#dep_id')
        .should('have.value', '--เลือกกรม--')
        cy.get(':nth-child(7) > .row > .col-md-12 > .form-control')
        .should('have.value', '--เลือกหน่วยงาน--')
    })
})
